### ISSUE TITLE
Contrast Issue on white text

### ISSUE THREAD

**Issue by fi-ya** [fac21/week4-blog-SMCJ#26]
Background and foreground colours do not have a sufficient contrast ratio.
Check here- https://web.dev/color-contrast/?utm_source=lighthouse&utm_medium=devtools 
Low-contrast text is difficult or impossible for many users to read.
Failing elements - span.sm-white

Beautiful styling overall. Love the theme and colours.

**Comment by sevdas** [comment]
Here is a screenshot of the current contrast ratio. The Minimum recommended contrast ratio would be 3.1! 
<img width="411" alt="Screenshot 2021-04-16 at 10 27 16" src="https://user-images.githubusercontent.com/63476393/115004381-a8dcdc00-9e9e-11eb-9c38-d2f7e25d1538.png">
